"""Phase C1: the latent-space planning loop (Experiment 3, stage 1).
First actual planning runs: PGD over a_{1:T} through the Phase-B predictors
under three goal costs, with the Section-6 telemetry stack (tripwire,
eps*T watchdog + CEM fallback, non-colinearity, wall-clock). Tasks are
self-reachable: the goal is generated by the SAME predictor with random
actions, so a witness exists and the experiment isolates the OPTIMIZER."""
import time
import numpy as np
import torch
from degp.planner import AsymmetricQuasiMetric
from degp.leash import weight_normalize_


def batched_rollout(model, z0, A):
    """z0: (K,), A: (B, T, Na) -> z_T: (B, K)."""
    z = z0.unsqueeze(0).expand(A.shape[0], -1)
    for t in range(A.shape[1]):
        z = model(z, A[:, t])
    return z


def make_task(model, K, Na, T, seed, act_scale=0.5):
    g = torch.Generator().manual_seed(seed + 7777)
    z0 = torch.randn(K, generator=g)
    a_star = torch.randn(T, Na, generator=g) * act_scale
    with torch.no_grad():
        z_goal = batched_rollout(model, z0, a_star.unsqueeze(0)).squeeze(0)
    return z0, a_star, z_goal


def build_dq(K, M, C_W, seed):
    torch.manual_seed(seed + 31)
    dq = AsymmetricQuasiMetric(K, M)
    weight_normalize_(dq, C_W)
    for p in dq.parameters(): p.requires_grad_(False)
    return dq


def make_costs(dq, mu):
    euc = lambda zT, zg: ((zT - zg) ** 2).sum(-1)
    unl = lambda zT, zg: dq(zT, zg.unsqueeze(0).expand_as(zT))
    return {'euclidean': euc, 'unleashed': unl,
            'leashed': lambda zT, zg: unl(zT, zg) + mu * euc(zT, zg)}


def pgd_plan(model, z0, z_goal, cost_fn, T, Na, lr, iters, tol=0.5,
             a_max=3.0, eps=None, budget=0.5, watchdog=False, stall=60):
    alarm = (eps is not None) and (eps * T > budget)
    a = torch.zeros(T, Na, requires_grad=True, device=z0.device)
    gap_h, dq_h, ang_h = [], [], []
    t0 = time.time(); best, best_it, it_tol = float('inf'), 0, None
    for it in range(iters):
        zT = batched_rollout(model, z0, a.unsqueeze(0)).squeeze(0)
        L = cost_fn(zT.unsqueeze(0), z_goal).sum()
        (ga, gzT) = torch.autograd.grad(L, (a, zT))
        with torch.no_grad():
            delta = zT - z_goal
            gap = delta.norm().item()
            dqv = cost_fn.__name__          # placeholder replaced below
        # -- telemetry (cheap, no_grad) --
        with torch.no_grad():
            cos = torch.nn.functional.cosine_similarity(gzT, delta, dim=0).clamp(-1, 1)
            ang = torch.rad2deg(torch.acos(cos)).item()
            if gap < best - 1e-6: best, best_it = gap, it
            if it_tol is None and gap < tol: it_tol = it
            gap_h.append(gap); ang_h.append(ang)
            if watchdog and alarm and it > stall and (it - best_it) > stall:
                return dict(gap=np.array(gap_h), angle=np.array(ang_h), a=a.detach(),
                            success=False, iters_to_tol=it_tol, fallback=True,
                            wall_time=time.time() - t0, final_gap=gap)
        with torch.no_grad():
            a = (a - lr * ga).clamp(-a_max, a_max)
        a.requires_grad_(True)
    return dict(gap=np.array(gap_h), angle=np.array(ang_h), a=a.detach(),
                success=bool(gap_h[-1] < tol), iters_to_tol=it_tol, fallback=False,
                wall_time=time.time() - t0, final_gap=gap_h[-1])


def cem_plan(model, z0, z_goal, cost_fn, T, Na, pop=500, elites=50, iters=5,
             init_std=0.5, a_max=3.0, tol=0.5, seed=0):
    g = torch.Generator().manual_seed(seed + 555)
    mean = torch.zeros(T, Na, device=z0.device); std = torch.full((T, Na), float(init_std), device=z0.device)
    t0 = time.time(); best_gap, it_tol = float('inf'), None
    for it in range(iters):
        A = (mean + std * torch.randn(pop, T, Na, generator=g).to(z0.device)).clamp(-a_max, a_max)
        with torch.no_grad():
            zT = batched_rollout(model, z0, A)
            costs = cost_fn(zT, z_goal)
            gaps = (zT - z_goal).norm(dim=-1)
            order = costs.argsort()[:elites]
            best_gap = min(best_gap, gaps[order[0]].item())
            if it_tol is None and best_gap < tol: it_tol = it
            mean, std = A[order].mean(0), A[order].std(0).clamp_min(0.05)
    return dict(a=mean, success=bool(best_gap < tol), final_gap=best_gap,
                iters_to_tol=it_tol, wall_time=time.time() - t0)
